### ISSUE TITLE
Dependency graph

### ISSUE THREAD

**Issue by LecrisUT** [blinxen/fedtools#1]
From the [`chain-build.toml`](https://github.com/blinxen/fedtools/blob/main/example/chain-build.toml) example, is it that the dependency graph has to be computed manually?

**Comment by HusseinKabbout** [comment]
For now yes, you have to specify the order of the builds.

**Comment by blinxen** [comment]
For now yes, you have to specify the order of the builds.

**Comment by blinxen** [comment]
I should also mention that the SRPM is built locally. That means that you need to have each packages in a directory with their spec file.
